import { PermissionsString } from "discord.js";
import PermissionCategory from "../structures/common/PermissionCategory";

export default {
    AddReactions: "text",
    Administrator: "advanced",
    AttachFiles: "text",
    BanMembers: "membership",
    ChangeNickname: "membership",
    Connect: "voice",
    CreateInstantInvite: "membership",
    CreatePrivateThreads: "text",
    CreatePublicThreads: "text",
    DeafenMembers: "voice",
    EmbedLinks: "text",
    KickMembers: "membership",
    ManageChannels: "general",
    ManageEmojisAndStickers: "general",
    ManageEvents: "events",
    ManageGuild: "general",
    ManageMessages: "text",
    ManageNicknames: "membership",
    ManageRoles: "general",
    ManageThreads: "text",
    ManageWebhooks: "general",
    MentionEveryone: "text",
    ModerateMembers: "membership",
    MoveMembers: "voice",
    MuteMembers: "voice",
    PrioritySpeaker: "voice",
    ReadMessageHistory: "text",
    RequestToSpeak: "stage",
    SendMessages: "text",
    SendMessagesInThreads: "text",
    SendTTSMessages: "text",
    Speak: "voice",
    Stream: "voice",
    UseApplicationCommands: "apps",
    UseEmbeddedActivities: "apps",
    UseExternalEmojis: "text",
    UseExternalStickers: "text",
    UseVAD: "voice",
    ViewAuditLog: "general",
    ViewChannel: "general",
    ViewGuildInsights: "general",
    ManageGuildExpressions: "general",
    SendVoiceMessages: "text",
    UseExternalSounds: "voice",
    UseSoundboard: "voice",
    ViewCreatorMonetizationAnalytics: "advanced",
    CreateEvents: "events",
    CreateGuildExpressions: "general",
    SendPolls: "text",
    UseExternalApps: "apps"
} satisfies {
    [name in PermissionsString]: PermissionCategory;
};
